version: '3.7'

services:
  grafana:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000" # Grafana
      - "4317:4317" # OpenTelemetry
      - "4318:4318" # OpenTelemetry
      - "9090:9090" # Prometheus
      - "3100:3100" # Loki
    volumes:
      - grafana_data:/data
    networks:
      - grafana_network
      - traefik_network  # Add this line
    deploy:
      mode: replicated
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.skyceer.com`)"
        - "traefik.http.routers.grafana.entrypoints=websecure" # Changed to websecure (port 443)
        - "traefik.http.routers.grafana.tls=true" # Enable TLS
        - "traefik.http.routers.grafana.tls.certresolver=letsencrypt" # Use Let’s Encrypt resolver
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      replicas: 1
      # placement:
        # constraints:
        #   - node.role == manager

networks:
  grafana_network:
    driver: overlay
    attachable: true
  traefik_network:
    driver: overlay
    attachable: true

volumes:
  grafana_data: