version: '3.2'

services:
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # Enable Service discovery for Traefik
        - "traefik.enable=true"
        # Define the portainer router rule
        - "traefik.http.routers.portainer.rule=Host(`portainer.skyceer.com`)"
        # Expose portainer on the HTTPS entrypoint
        - "traefik.http.routers.portainer.entrypoints=websecure"
        # Enable TLS
        - "traefik.http.routers.portainer.tls=true"
        # Expose the portainer port number to Traefik
        - traefik.http.services.portainer.loadbalancer.server.port=9443

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data: