version: '3.7'

services:
  postgresql-master:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432" # Published on port 5432 of the ingress network
    volumes:
      - postgresql_master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
    networks:
      - postgres_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.postgresql-master.rule=Host(`postgresql-master.skyceer.com`)"
        - "traefik.http.routers.postgresql-master.entrypoints=websecure" # Changed to websecure (port 443)
        - "traefik.http.routers.postgresql-master.tls=true" # Enable TLS
        - "traefik.http.routers.postgresql-master.tls.certresolver=letsencrypt" # Use Let’s Encrypt resolver
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.labels.hostname == postgresql_master

  postgresql-slave-1:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432" # Published on port 5433 of the ingress network
    volumes:
      - postgresql_slave_data_1:/bitnami/postgresql
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    networks:
      - postgres_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.postgresql-slave-1.rule=Host(`postgresql-slave-1.skyceer.com`)"
        - "traefik.http.routers.postgresql-slave-1.entrypoints=websecure" # Changed to websecure (port 443)
        - "traefik.http.routers.postgresql-slave-1.tls=true" # Enable TLS
        - "traefik.http.routers.postgresql-slave-1.tls.certresolver=letsencrypt" # Use Let’s Encrypt resolver
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.labels.hostname == postgresql-slave-1

networks:
  postgres_network:
    driver: overlay
    attachable: true

volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave_data_1:
    driver: local