version: '3.8'

services:
  mongodb-primary:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    # volumes:
    #   - mongodb_master_data:/bitnami
    networks:
      - mongodb_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mongodb-secondary:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - mongodb_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mongodb-arbiter:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - mongodb_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb-primary
    ports:
      # Expose Mongo Express web interface on host port 8081
      - '8081:8081' 
    environment:
      # https://hub.docker.com/_/mongo-express

      # --- Mongo Express Web Interface Basic Authentication ---
      - ME_CONFIG_BASICAUTH_USERNAME=admin_me
      - ME_CONFIG_BASICAUTH_PASSWORD=password_me123
      
      # --- MongoDB Connection Settings ---
      # Enable admin access (recommended for full functionality)
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # Use the root credentials from the MongoDB setup
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      # The server should be a comma-delimited list of all replica set members
      - ME_CONFIG_MONGODB_SERVER=mongodb-primary,mongodb-secondary,mongodb-arbiter
      - ME_CONFIG_MONGODB_PORT=27017
      
      # Set a unique secret for session cookies
      - ME_CONFIG_SITE_SESSIONSECRET=a_secret_for_mongo_express
      
      # Optional: set a custom title
      - ME_CONFIG_SITE_NAME=My Mongo Replica Set Explorer
    networks:
      - mongodb_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  mongodb_network:
    driver: overlay
    attachable: true

# volumes:
#   mongodb_master_data:
#     driver: local