version: '3.8'

services:
  postgresql-master:
    image: bitnami/postgresql:latest
    hostname: postgresql-master-hostname
    ports:
      - "5432:5432" # Published on port 5432 of the ingress network 
    volumes:
      - postgresql_master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
    networks:
      - postgres_network
      - traefik_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.labels.hostname == postgresql_master

  postgresql-slave-1:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432" # Published on port 5433 of the ingress network
    volumes:
      - postgresql_slave_data_1:/bitnami/postgresql
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master-hostname
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    networks:
      - postgres_network
      - traefik_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.labels.hostname == postgresql-slave-1

networks:
  postgres_network:
    driver: overlay
    attachable: true
  traefik_network:
    driver: overlay
    attachable: true

volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave_data_1:
    driver: local




# SAMPLE SCRIPT

# CREATE TABLE IF NOT EXISTS users (
#     user_id SERIAL PRIMARY KEY,
#     username VARCHAR(50) NOT NULL UNIQUE,
#     email VARCHAR(100) NOT NULL,
#     age INTEGER,
#     is_active BOOLEAN DEFAULT TRUE,
#     registration_date TIMESTAMP WITHOUT TIME ZONE
# );


# INSERT INTO users (
#     username,
#     email,
#     age,
#     registration_date
# )
# SELECT
#     'user_' || i::text AS username,
    
#     -- Alternative: Use the row number 'i' directly, padded/modified
#     'email_' || overlay(i::text placing lpad('', 10 - length(i::text), '0') from 1) || '@example.com' AS email,
    
#     floor(random() * (60-18+1) + 18)::int AS age,
#     NOW() - (random() * interval '365 days') AS registration_date
# FROM 
#     generate_series(1, 10000) AS s(i);



# SELECT COUNT(*) FROM users;
# SELECT * FROM users LIMIT 10;