version: '3.8'

services:
  skyceer-web:
    # image: pkphung2001/skyceer-rails:latest
    image: skyceer-rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails assets:precompile && bundle exec thrust bin/rails server"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - skyceer-web_data:/rails
    ports:
      - "81:80"
      - "444:443"
    stdin_open: true
    tty: true
    networks:
      - postgres-stack_postgres_network
      - mongo-stack_mongodb_network
      - search-stack_search_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure # Only restart if the command fails (non-zero exit code)
        max_attempts: 0         # Do not attempt to restart on failure (this is the key to 'run once')
      placement:
        constraints:
          - node.role == manager
          # - node.labels.hostname == postgresql_master
      # labels:
      #   - "traefik.enable=true"
      #   - "traefik.http.routers.skyceer-web.rule=Host(`skyceer-web.skyceer.com`)" # Unique hostname
      #   - "traefik.http.routers.skyceer-web.entrypoints=websecure"
      #   - "traefik.http.routers.skyceer-web.tls=true"
      #   - "traefik.http.routers.skyceer-web.tls.certresolver=letsencrypt"
      #   - "traefik.http.services.skyceer-web.loadbalancer.server.port=80" # Internal port for the service


  skyceer-job:
    # image: pkphung2001/skyceer-rails:latest
    image: skyceer-rails
    # Wait 10s to ensure database already setup by skyceer-web
    command: bash -c "sleep 10 && bin/jobs"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - skyceer_job_data:/rails
    depends_on:
      - skyceer-web
    networks:
      - postgres-stack_postgres_network
      - mongo-stack_mongodb_network
      - search-stack_search_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure # Only restart if the command fails (non-zero exit code)
        max_attempts: 0         # Do not attempt to restart on failure (this is the key to 'run once')
      placement:
        constraints:
          - node.role == manager
          # - node.labels.hostname == postgresql_master

volumes:
  skyceer-web_data:
  skyceer_job_data:

networks:
  traefik-stack_traefik_network:
    external: true

  grafana-stack_grafana_network:
    external: true

  postgres-stack_postgres_network:
    external: true
  mongo-stack_mongodb_network:
    external: true
  search-stack_search_network:
    external: true

