version: '3.8'

services:
  opentelemetry:
    image: grafana/otel-lgtm
    ports:
      - "3001:3000" # Grafana
      - "4317:4317" # OpenTelemetry
      - "4318:4318" # OpenTelemetry
      - "9090:9090" # Prometheus
      - "3100:3100" # Loki
    volumes:
      - grafana_data:/data
    networks:
      - grafana_network
    deploy:
      mode: replicated
      replicas: 1
      # placement:
        # constraints:
        #   - node.role == manager

networks:
  grafana_network:
    driver: overlay
    attachable: true

volumes:
  grafana_data: